#!/usr/bin/env python3
"""شهاب — the site-wide type size.

The reader picks small / medium / large from the topbar (or the phone menu),
the choice lands on <html data-sh-type="sm|lg"> before the first paint, and this
sheet makes it true. The theme sets its type in pixels -- a thousand
declarations across forty sheets, on purpose (see the head of css/tokens.css) --
so nothing is converted: every rule in the content sheets that sets a
font-size is written again here, under the attribute, at ×0.92 and ×1.12.

What scales: the content -- css/components.css, css/gallery.css and every
css/pages/*.css. What does not: the chrome. The masthead, the topbar, the nav,
the ticker, the footer, the player and the toolbars keep their size, so the
reader's text grows and the interface stays where it was.

Small never takes a size below 12px: values already under 12 are left alone,
and the rest floor at 12. On phones css/responsive.css's own 12px floor
(tools/a11y.py) still wins with !important, as it should.

A clamp() display size scales too, as calc(clamp(...) * k). A size written as
calc(... * var(--reader-scale)) is left to that variable, which the article
sheet derives from the same attribute -- so long-form text is never scaled
twice.

    python tools/type.py        # rewrites css/type.css; run before tools/chrome.py
"""
import glob
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

OUT = 'css/type.css'
SHEETS = ['css/components.css', 'css/gallery.css'] + sorted(glob.glob('css/pages/*.css'))
STEPS = (('sm', 0.92), ('lg', 1.12))
FLOOR = 12.0
# the chrome, icons, marks and pseudo-elements stay as they are
SKIP = re.compile(r'\.sh-i\b|__i-\d|::|:before|:after|sh-mark|keyframes|\.vds-|media-player'
                  r'|\.sh-topbar|\.sh-masthead|\.sh-nav\b|\.sh-nav__|\.sh-header|\.sh-breaking|\.sh-ticker'
                  r'|\.sh-footer|\.sh-brief|\.sh-toast|\.sh-reader__|\.sh-ts\b|\.sh-ts__|\.sh-wx|\.sh-fx|\.sh-consent')
PX = re.compile(r'(?:^|;)\s*font-size\s*:\s*([0-9.]+)px\s*(!important)?\s*(?:;|$)')
CLAMP = re.compile(r'(?:^|;)\s*font-size\s*:\s*(clamp\([^)]*\))\s*(!important)?\s*(?:;|$)')


def fmt(v):
    return ('%.2f' % v).rstrip('0').rstrip('.')


def scale(n, step, k):
    if step == 'sm':
        if n < FLOOR:
            return None            # already at the floor: leave it
        return max(FLOOR, n * k)
    return n * k


def rules_of(block):
    """(selector, body) pairs of one brace-level of CSS."""
    for m in re.finditer(r'([^{}]+)\{([^{}]*)\}', block):
        sel = m.group(1).strip()
        if sel and not sel.startswith('@'):
            yield sel, m.group(2)


def walk(css):
    """Yield (media_query_or_None, selector, body), descending one @media level."""
    pos = 0
    for mm in re.finditer(r'@media[^{]+\{', css):
        for sel, body in rules_of(css[pos:mm.start()]):
            yield None, sel, body
        depth, i = 1, mm.end()
        while depth and i < len(css):
            depth += css[i] == '{'
            depth -= css[i] == '}'
            i += 1
        for sel, body in rules_of(css[mm.end():i - 1]):
            yield css[mm.start():mm.end() - 1].strip(), sel, body
        pos = i
    for sel, body in rules_of(css[pos:]):
        yield None, sel, body


def build():
    plain = {'sm': [], 'lg': []}
    media = {'sm': {}, 'lg': {}}
    read = 0
    for f in SHEETS:
        css = open(f, encoding='utf-8').read()
        css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)
        for q, sel, body in walk(css):
            parts = [p.strip() for p in sel.split(',') if p.strip() and not SKIP.search(p)]
            if not parts:
                continue
            px, cl = PX.search(body), CLAMP.search(body)
            if not px and not cl:
                continue
            read += 1
            for step, k in STEPS:
                if px:
                    v = scale(float(px.group(1)), step, k)
                    if v is None:
                        continue
                    val = fmt(v) + 'px' + ('!important' if px.group(2) else '')
                else:
                    val = 'calc(%s * %s)' % (cl.group(1), k) + ('!important' if cl.group(2) else '')
                sels = ','.join('html[data-sh-type="%s"] %s' % (step, p) for p in parts)
                line = '%s{font-size:%s}' % (sels, val)
                if q:
                    media[step].setdefault(q, []).append(line)
                else:
                    plain[step].append(line)
    out = ['/* شهاب — generated by tools/type.py; do not edit. The site-wide type size:',
           '   every content font-size again under html[data-sh-type="sm"] (×0.92, floor',
           '   12px) and ="lg" (×1.12). The chrome is not here on purpose. */']
    for step, k in STEPS:
        out.append('\n/* ---- %s ×%s (%d rules) ---- */' % (step, k, len(plain[step]) + sum(len(v) for v in media[step].values())))
        out.extend(plain[step])
        for q, lines in media[step].items():
            out.append(q + '{')
            out.extend('  ' + l for l in lines)
            out.append('}')
    open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
    total = sum(len(plain[s]) + sum(len(v) for v in media[s].values()) for s, _ in STEPS)
    print('type scale: %d font-size rules read, %d written -> %s (%d KB)' % (read, total, OUT, os.path.getsize(OUT) // 1024))


if __name__ == '__main__':
    build()
